window:
  dimensions:
   columns: 82
   lines: 25
  padding:
   x: 20
   y: 20
  decorations: full
  opacity: 0.8
  startup_mode: Windowed
  dynamic_title: true
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: "Monocraft"
    style: Regular
  bold:
    family: "Monocraft"
    style: Bold
  italic:
    family: "Monocraft"
    style: Italic
  bold_italic:
    family: "Monocraft"
    style: Bold Italic
  size: 10

colors:
  # Default colors
  primary:
   background: '#070219'
   foreground: '#c0caf5'

  # Normal colors
  normal:
   black:   '#070219'
   red:     '#fb007a'
   green:   '#a6e22e'
   yellow:  '#f3e430'
   blue:    '#58AFC2'
   magenta: '#583794'
   cyan:    '#926BCA'
   white:   '#d9d9d9'

  # Bright colors
  bright:
   black:   '#626483'
   red:     '#fb007a'
   green:   '#a6e22e'
   yellow:  '#f3e430'
   blue:    '#58AFC2'
   magenta: '#472575'
   cyan:    '#926BCA'
   white:   '#f1f1f1'

cursor:
  style:
    shape: Block
    blinking: On
  unfocused_hollow: true

live_config_reload: true

hints:
  enabled:
  - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
            [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    hyperlinks: true
    command: xdg-open