live_config_reload = true

[colors.bright]
black = "#454545"
blue = "#556FFF"
cyan = "#3FDCEE"
green = "#18E3C8"
magenta = "#B043D1"
red = "#FF4971"
white = "#BEBEC1"
yellow = "#FF8037"

[colors.normal]
black = "#1f1d1b"
blue = "#8897F4"
cyan = "#79E6F3"
green = "#5ADECD"
magenta = "#C574DD"
red = "#F37F97"
white = "#FDFDFD"
yellow = "#F2A272"

[colors.primary]
background = "#1D1F28"
foreground = "#FDFDFD"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 0.7
startup_mode = "Windowed"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 82
lines = 25

[window.padding]
x = 20
y = 20
