#!/usr/bin/env bash

SFILE="$HOME/.config/punk_records/scripts/system.ini"

if [[ ! -f "$SFILE" ]]; then
	touch "$SFILE"
	chmod a+rwx "$SFILE"
	cat > $SFILE << EOF
;  ╔═╗╦ ╦╔═╗╔╦╗╔═╗╔╦╗  ╦  ╦╔═╗╦═╗╦╔═╗╔╗ ╦  ╔═╗╔═╗
;  ╚═╗╚╦╝╚═╗ ║ ║╣ ║║║  ╚╗╔╝╠═╣╠╦╝║╠═╣╠╩╗║  ║╣ ╚═╗
;  ╚═╝ ╩ ╚═╝ ╩ ╚═╝╩ ╩   ╚╝ ╩ ╩╩╚═╩╩ ╩╚═╝╩═╝╚═╝╚═╝
; The variables for the polybar modules are taken from this file.

;; Edit according to your system
;; Run "ls -1 /sys/class/power_supply/" to list list adapters and batteries.
;; Run "ls -1 /sys/class/backlight/" to list available graphics cards.
;; Run "ip link | awk '/state UP/ {print $2}' | tr -d :" to get active network interface.
;; Run "xrandr | grep "connected primary" | awk '{print $1}'" to get the name of the currently connected primary monitor.
;; Run "xrandr | grep "connected" | grep -v "primary" | awk '{print $1}'" to get the name of the external monitor.

[system]
sys_adapter = 
sys_battery = 
sys_graphics_card = 
sys_network_interface = 
internal_monitor = 
external_monitor = 
EOF

fi

function get_values() {

	DEFNETWORK=$(ip route | grep '^default' | awk '{print $5}' | head -n1)
	CARD=$(ls -1 /sys/class/backlight/)
	power_supply_files=$(ls /sys/class/power_supply/)

		for file in $power_supply_files
			do
				if [ -e "/sys/class/power_supply/$file/capacity" ]; then
					battery_file=$file
				fi

				if [ -e "/sys/class/power_supply/$file/online" ]; then
					adapter_file=$file
				fi
			done

	BATTERY="$battery_file"
	ADAPTER="$adapter_file"
	INTERNAL_MONITOR=$(xrandr | grep "connected primary" | awk '{print $1}')
	EXTERNAL_MONITOR=$(xrandr | grep "connected" | grep -v "primary" | awk '{print $1}')
}

function set_values() {

	if [[ "$DEFNETWORK" ]]; then
		sed -i -e "s/sys_network_interface = .*/sys_network_interface = $DEFNETWORK/g" $HOME/.config/punk_records/scripts/system.ini
	fi
	if [[ "$ADAPTER" ]]; then
		sed -i -e "s/sys_adapter = .*/sys_adapter = $ADAPTER/g" $HOME/.config/punk_records/scripts/system.ini
	fi
	if [[ "$BATTERY" ]]; then
		sed -i -e "s/sys_battery = .*/sys_battery = $BATTERY/g" $HOME/.config/punk_records/scripts/system.ini
	fi
	if [[ "$CARD" ]]; then
		sed -i -e "s/sys_graphics_card = .*/sys_graphics_card = $CARD/g" $HOME/.config/punk_records/scripts/system.ini
	fi
	if [[ "$INTERNAL_MONITOR" ]]; then
		sed -i -e "s/internal_monitor = .*/internal_monitor = $INTERNAL_MONITOR/g" $HOME/.config/punk_records/scripts/system.ini
	fi
	if [[ "$EXTERNAL_MONITOR" ]]; then
		sed -i -e "s/external_monitor = .*/external_monitor = $EXTERNAL_MONITOR/g" $HOME/.config/punk_records/scripts/system.ini
	fi
}

get_values
set_values
