#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝

########### Def vars
read -r RICETHEME < "$HOME"/.config/punk_records/.rice
export RICETHEME
PATH="$HOME/.config/punk_records/scripts:$PATH"
rice_dir="$HOME/.config/punk_records/rices/$RICETHEME"
export XDG_CURRENT_DESKTOP='bspwm'

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

# change these values according to your system
# you can use `xrandr -q` to get the names of monitors
INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1"
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
	bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8' 
	bspc monitor "$EXTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8' 
	bspc wm -O  "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
else
	bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8'
fi

########### bspwm conf

bspc config external_rules_command ~/.config/bspwm/external_rules

bspc config window_gap                    2
bspc config split_ratio                   0.5
bspc config single_monocle                true
bspc config borderless_monocle            false
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled			  true
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner
bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child
bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true
bspc config pointer_motion_interval       16


#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

# Set system vars for polybar
. SetSysVars

# Terminate already running polybar, stalonetray, sxhkd and dunst instances
processes=("sxhkd" "polybar" "dunst" "eww.*bar")

for process in "${processes[@]}"; do
    if pgrep -f "$process"; then
        pkill -f "$process" > /dev/null; sleep 0.25
    fi
done

# Load bspwm conf, colors, dunst, bars and/or eww widgets
. "${rice_dir}"/Theme.sh

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/punk_records/sxhkdrc &

# Launch picom // If you have old hardware or encounter problems
# uncomment the picom "--legacy-backends" line and comment the current one.
pidof -q picom || { picom --config "$HOME"/.config/punk_records/picom.conf & }
#pidof -q picom || { picom --legacy-backends --config "$HOME"/.config/bspwm/picom.conf & }

# Launch dunst notification daemon
dunst -config "$HOME"/.config/punk_records/dunstrc &

# Set random wallpaper for actual rice
feh -z --no-fehbg --bg-fill "${rice_dir}"/walls

# Launch eww daemon
pidof -q eww || { eww -c "$HOME"/.config/punk_records/eww daemon & }

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor
xsetroot -cursor_name left_ptr