#!/usr/bin/env bash

wid=$1
class=$2
instance=$3
consequences=$4

result() {
    eval "$consequences"
    [ "$state" ] || echo "$1"
}

case "$class" in
    FloaTerm)
        result "state=floating center=on"
        ;;
    Updating)
        result "state=floating sticky=on center=on"
        ;;
    mpv)
        result "state=floating focus=on rectangle=925x519+0+0 center=on"
        ;;
    Pavucontrol)
        result "state=floating follow=on center=on"
        ;;
    ranger)
        result "state=floating rectangle=811x316+0+0 center=on"
        ;;
    fetch)
        result "state=floating rectangle=392x642+487+63"
        ;;
    ######################################################
    Thunar)
        result "state=pseudo_tiled desktop=^2 rectangle=966x576+0+0 follow=on"
        ;;
    Google-chrome|firefox)
        result "desktop=^3 follow=on focus=on"
        ;;
    Code|jetbrains-studio)
        result "desktop=^4 follow=on focus=on"
        ;;
    wps|et|wpp)
        result "desktop=^5 follow=on focus=on"
        ;;
    whatsapp-nativefier-d40211|TelegramDesktop|Slack)
        result "state=pseudo_tiled desktop=^6 focus=on follow=on rectangle=930x617+0+0"
        ;;
    Spotify|spicetify|ncmpcpp)
        result "desktop=^7  follow=on focus=on"
        ;;
    "")
	    # Fix: Spotify not following bspc rule
		sleep 0.5
		wm_class=($(xprop -id $wid | grep "WM_CLASS" | grep -Po '"\K[^,"]+'))
		class=${wm_class[-1]}
		[[ ${#wm_class[@]} == "2" ]] && instance=${wm_class[0]}
		[[ -n "$class" ]] && main
		;;
		######################################
    discord|obs)
        result "desktop=^8 follow=on focus=on"
esac

case "$instance" in
    Toolkit)
        result "state=floating sticky=on rectangle=500x290+1054+593"
        ;;
esac