#!/usr/bin/env bash

RED=$(tput setaf 1)
GRN=$(tput setaf 2)
YLW=$(tput setaf 3)
BLU=$(tput setaf 4)
MGT=$(tput setaf 5)
CYN=$(tput setaf 6)
WHT=$(tput setaf 7)
BLD=$(tput bold)
RST=$(tput sgr0)

display_logo () {
	printf "
                        $BLU.
                       $BLU/ $MGT\\
                      $BLU/   $MGT\\
                     $BLU/^.   $MGT\\
                    $BLU/  .$WHT-$MGT.  \\
                   $BLU/  (   $MGT) _\\
                  $BLU/ _.~   $MGT~._^\\
                 $BLU/.^         $MGT^.\\

	"
    printf "$RED󰮯   $CYN   $YLW󰊠   $WHT   $MGT󰊠   $GRN   $BLU󰊠   $RED   $WHT󰮯\n"
}

info_msg() {
    printf '\n\n%s%s[ %s ] %s\n\n' "${BLD}" "${BLU}" "${1:?}" "${RST}"
}
selection() {
    printf '%s%s%s)%s %s%s%s\n' "${BLD}" "${CYN}" "${1:?}" "${RST}" "${WHT}" "${2:?}" "${RST}"
}
success_msg() {
    printf '%s%s %s %s\n' "${BLD}" "${GRN}" "${1:?}" "${RST}"
}
installing_msg() {
    printf '%s%s %s %s\n' "${BLD}" "${WHT}" "${1:?}" "${RST}"
}
warning_msg() {
    printf '%s%s %s %s\n' "${BLD}" "${YLW}" "${1:?}" "${RST}"
}
error_msg() {
    printf '%s%s %s %s\n' "${BLD}" "${RED}" "${1:?}" "${RST}"
}

########## ---------- Warning ---------- ##########
display_logo
info_msg "Welcome!"

if [ "$(id -u)" = 0 ]; then
    warning_msg "This script MUST NOT be run as root user"
    exit 1
fi

while true; do
    read -rp "$BLD$YLW- This script configures my personal Arch setup. Do you wish to continue (NOT recommended) ? [y/N]: $RST" yn
    case $yn in
        [Yy]* ) break ;;
        [Nn]* ) exit ;;
        *) error_msg "Error: just write 'y' or 'n'" ;;
    esac
done
clear

########## ---------- Utility Functions ---------- ##########
check_xprofile() {
    if [ ! -f ~/.xprofile ]; then
        touch ~/.xprofile
        chmod 644 ~/.xprofile
    fi
}

check_install_dependencies() {
    # https://wiki.archlinux.org/title/AUR_helpers#Pacman_wrappers
    pacman_wrappers="paru"

    local dependencies="$1"
    local missing=()

    # Split the string into an array using space as delimiter
    IFS=' ' read -r -a deps <<< "$dependencies"

    is_installed() {
        pacman -Q "$1" &> /dev/null
    }
    installing_msg "Checking for required packages..."

    for package in "${deps[@]}"; do
        if ! is_installed "$package"; then
            missing+=("$package")
        else
            warning_msg "   '$package' is already installed on your system!"
            sleep 1
        fi
    done

    if [ ${#missing[@]} -gt 0 ]; then
        for package in "${missing[@]}"; do
            if $pacman_wrappers -S "$package" --noconfirm >/dev/null 2>&1; then
                success_msg "   '$package' has been installed successfully"
                sleep 1
            else
                error_msg "   Failed to install '$package'. You may need to install it manually"
                sleep 1
            fi
        done
    fi
    printf "\n"
}
########## ---------- Functional components ---------- ##########
Vietnamese_ime_config() {
    info_msg "Install a Vietnamese IME for IBus"

    check_install_dependencies "ibus"

    if command -v ibus >/dev/null 2>&1; then
        check_install_dependencies "ibus-bamboo"
    fi

    # Ensure .xprofile exists and is writable
    check_xprofile

    # Add necessary environment variables to ~/.xprofile
    if ! grep -Fxq "# export IBus env and start IBus daemon" ~/.xprofile; then
        {
            printf '\n# export IBus env and start IBus daemon\n'
            echo 'export GTK_IM_MODULE=ibus'
            echo 'export XMODIFIERS=@im=ibus'
            echo 'export QT_IM_MODULE=ibus'
            # set IBus as the default input method
            echo 'export DefaultIMModule=ibus'
            # Start IBus daemon automatically
            printf 'ibus-daemon -drx\n'
        } | tee -a ~/.xprofile > /dev/null
    fi

    printf "\n"

    if gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Control>space']" >/dev/null 2>> RiceError.log; then
        success_msg "Set keybinding for the next input method to '<Control>space' successfully"
    else
        error_msg "Failed to set keybinding. See ~/RiceError.log for more details"
    fi

    #gsettings set org.freedesktop.ibus.general preload-engines "['xkb:us::eng', 'xkb:vn::vie']"
    if gsettings set org.freedesktop.ibus.general preload-engines "['BambooUs', 'Bamboo']" >/dev/null 2>> RiceError.log; then
        success_msg "Configure input methods successfully: Vietnamese - English"
    else
        error_msg "Failed to configure input methods. See ~/RiceError.log for more details"
    fi

    sleep 2
}

adjust_brightness() {
    info_msg "Adjust contrast and brightness"

    check_install_dependencies "xorg-xgamma brightnessctl"

    # New values
    new_gamma=0.8
    new_brightness_percent=100
       
    # Command strings
    xgamma_command="xgamma -gamma ${new_gamma}"
    brightnessctl_command="brightnessctl s ${new_brightness_percent}%"

    # Ensure .xprofile exists and is writable
    check_xprofile

    # Apply new settings
    if $xgamma_command 2> /dev/null; then
        if grep -Fq "xgamma -gamma" ~/.xprofile; then
            sed -i "/xgamma -gamma/c\\$xgamma_command" ~/.xprofile
            success_msg "Contrast adjusted to ${new_gamma} successfully"
        else
            {
                printf "\n# Contrast adjustment\n"
                printf "$xgamma_command\n" 
            } | tee -a ~/.xprofile > /dev/null
            success_msg "Contrast adjusted to ${new_gamma} successfully"
        fi
    else
        error_msg "Failed to adjust contrast"
    fi

    if $brightnessctl_command > /dev/null; then
        success_msg "Brightness adjusted to ${new_brightness_percent}% successfully"
    else
        error_msg "Failed to adjust brightness"
    fi

    sleep 2
}

setup_audio() {
    info_msg "Setup audio/sound"

    check_install_dependencies "alsa-utils pipewire pipewire-alsa pipewire-jack pipewire-pulse"

    #By default, ALSA has all channels muted. Those have to be unmuted manually.
    #Unmute with amixer
    amixer sset Master unmute 50% > /dev/null

    #Enable and start pipewire
    systemctl --user enable pipewire > /dev/null 2>> RiceError.log
    systemctl --user start pipewire > /dev/null 2>> RiceError.log

    success_msg "Basic audio setup completed"

    sleep 2
}

change_dns_server() {
    info_msg "Change default DNS server to Google DNS"

    google_dns="static domain_name_servers=8.8.4.4 8.8.8.8"

    if ! grep -Fxq "$google_dns" /etc/dhcpcd.conf; then
        echo "$google_dns" | sudo tee -a /etc/dhcpcd.conf > /dev/null
        success_msg "Change default DNS server successfully"
    else
        warning_msg "Google DNS server already configured"
    fi

    sleep 2
}

config_touchpad() {
    info_msg "Enable touchpad tapping, natural scrolling"

    local file_path="/etc/X11/xorg.conf.d/30-touchpad.conf"

    if [ ! -f "$file_path" ]; then
        sudo tee "$file_path" > /dev/null << EOF
Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lmr"
    Option "NaturalScrolling" "true"
EndSection
EOF
        success_msg "Enable touchpad tapping and natural scrolling successfully"
    else
        warning_msg "Touchpad configuration already existed"
    fi

    sleep 2
}

connect_external_monitor()  {
    info_msg "Connect to the external monitor immediately"

    local INTERNAL_DISPLAY=$(xrandr | grep "connected primary" | awk '{print $1}')
    local EXTERNAL_DISPLAY=$(xrandr | grep "connected" | grep -v "primary" | awk '{print $1}')

    if xrandr --output "$INTERNAL_DISPLAY" --auto --output "$EXTERNAL_DISPLAY" --auto --right-of "$INTERNAL_DISPLAY"; then
        success_msg "Connect to the external monitor successfully"
    fi
    
    sleep 2
}

install_and_configure_all() {
    Vietnamese_ime_config
    adjust_brightness
    setup_audio
    change_dns_server
    config_touchpad
    connect_external_monitor

    printf "\n"
    success_msg "Installation finished !"
}

########## ---------- Main menu ---------- ##########
show_menu() {
    display_logo
    info_msg "Select an option"

    selection 1 "Install a Vietnamese IME for IBus"
    selection 2 "Adjust contrast and brightness"
    selection 3 "Setup audio/sound"
    selection 4 "Change default DNS server to Google DNS"
    selection 5 "Enable touchpad tapping, natural scrolling"
    selection 6 "Connect to the external monitor immediately"
    selection 7 "All"
    selection 8 "Exit"

    printf '\n%s%sEnter your choice [1-8]: %s' "${BLD}" "${YLW}" "${RST}"
}

while true; do
    show_menu
    read choice
    case $choice in
        1) Vietnamese_ime_config ;;
        2) adjust_brightness ;;
        3) setup_audio ;;
        4) change_dns_server ;;
        5) config_touchpad ;;
        6) connect_external_monitor ;;
        7) install_and_configure_all; break ;;
        8) echo "Exiting..."; exit 0 ;;
        *) echo "Invalid option, please try again." ;;
    esac
done
